/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PaseExample1 */

#ifndef _Included_PaseExample1
#define _Included_PaseExample1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PaseExample1
 * Method:    getStringNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_PaseExample1_getStringNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
